name:                       golang-pipeline
on:                         push
jobs:
  test:
    runs-on:                ubuntu-latest
    if:                     github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
    steps:
      - uses:               actions/checkout@v2
      - name:               Run Unit Tests
        working-directory:  ./atlas.com/ros
        run:                go test

  deploy:
    runs-on:                ubuntu-latest
    needs:                  test
    if:                     ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    steps:
      - name:               Login to DockerHub
        uses:               docker/login-action@v1
        with:
          username:         ${{ secrets.DOCKER_USERNAME }}
          password:         ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name:               Build and push
        uses:               docker/build-push-action@v2
        with:
          push:             true
          tags:             jtumidanski/atlas-ros:latest
